name: Шангин Николай
description: Моё общественное пространство
avatar: /images/logo.svg

footer-links:
  dribbble:
  email: shanginn@gmail.com
  facebook:
  flickr:
  github: shanginn
  instagram: shanginn
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: shanginn
  stackoverflow: users/2457191/shanginn # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +НиколайШангин # anything in your profile username that comes after plus.google.com/

disqus: shanginn

google_analytics: UA-73429383-1
yandex_metrica: 35344295

# Used for Sitemap.xml and RSS feed
url: http://shanginn.ru
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title/
future: true

# The release of Jekyll Now that you're using
version: v3.1.1

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: assets/_sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
